---
- hosts: localhost
  connection: local
  tasks:
    - debug: msg='Install office'
    - block:
      - apt:
          force_apt_get: yes
          name:
            - libreoffice
            - xsane
          state: latest
      when: ansible_os_family == 'Debian' # @TODO: ubuntu
# @TODO: manjaro
# @TODO: fedora
