---
- hosts: localhost
  connection: local
  tasks:
    - debug: msg='Install chrome'
    - apt:
        force_apt_get: yes
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
