---
- hosts: localhost
  connection: local
  tasks:
    - debug: msg='Install keypairs'
    - file: path="{{ current_home }}/.ssh" state=directory force=no
    - copy: content="" dest="{{ current_home }}/.ssh/config" force=no
    - openssh_keypair: path="{{ current_home }}/.ssh/id_rsa" type=rsa size=4096 force=no
    - openssh_keypair: path="{{ current_home }}/.ssh/id_ed25519" type=ed25519 force=no
