---
- hosts: localhost
  connection: local
  tasks:
    - debug: msg='Install office'
    - apt:
        force_apt_get: yes
        name:
          - libreoffice
          - xsane
        state: latest