---
- hosts: localhost
  connection: local
  tasks:
    - debug: msg='Install playonlinux'
    - block:
      - apt: 
          force_apt_get: yes
          state: latest
          name: playonlinux
      when: ansible_os_family == 'Debian' # @TODO: ubuntu
# @TODO: manjaro
# @TODO: fedora
