---
- hosts: localhost
  connection: local
  tasks:
    - debug: msg='Install utils'
    - apt: force_apt_get=yes state=latest name=software-properties-common
    - apt_repository: repo=ppa:phoerious/keepassxc state=present update_cache=yes
    - apt:
        force_apt_get: yes
        name:
          - language-pack-ru
          - keepassxc
          - transmission
          - gimp
          - vlc
        state: latest
    - apt: 
        force_apt_get: yes
        name: 
          - language-pack-kde-ru
          - usb-creator-kde
        state: latest
      when: ansible_os_family == 'Debian' and ansible_env.XDG_CURRENT_DESKTOP is defined and ansible_env.XDG_CURRENT_DESKTOP == "KDE"
    - apt: 
        force_apt_get: yes
        name: 
          - language-pack-gnome-ru
          - usb-creator-gtk
          - variety
          - gnome-tweak-tool
        state: latest
      when: ansible_os_family == 'Debian' and ansible_env.XDG_CURRENT_DESKTOP is defined and ansible_env.XDG_CURRENT_DESKTOP == "GNOME"
    - apt: force_apt_get=yes deb=https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
