---
- hosts: localhost
  connection: local
  roles:
    - role: gantsign.visual-studio-code # https://github.com/gantsign/ansible-role-visual-studio-code
      users:
        - username: "{{ current_user }}"
          visual_studio_code_extensions:
            - ms-azuretools.vscode-docker
            - mikestead.dotenv
            - codezombiech.gitignore
            - yzhang.markdown-all-in-one
            - christian-kohler.path-intellisense
            - ms-vscode-remote.vscode-remote-extensionpack
            - wayou.vscode-todo-highlight
            - redhat.vscode-yaml
            - mhutchie.git-graph
            # - donjayamanne.githistory
            - eamodio.gitlens
      when: ansible_os_family == 'Debian' # @TODO: ubuntu
# @TODO: manjaro
# @TODO: fedora
