---
- hosts: localhost
  connection: local
  tasks:
    - apt: force_apt_get=yes deb='{{item}}'
      with_items:
      - https://repo.skype.com/latest/skypeforlinux-64.deb
      - https://zoom.us/client/latest/zoom_amd64.deb
      - https://discord.com/api/download?platform=linux&format=deb
    - get_url: url=https://telegram.org/dl/desktop/linux dest={{ current_home }}/soft/telegram.tar.xz
    # telegram (https://telegram.org/dl/desktop/linux, https://updates.tdesktop.com/tlinux/tsetup.3.7.3.tar.xz)
