---
- hosts: localhost
  connection: local
  tasks:
    - apt:
        force_apt_get: yes
        name:
          - apt-transport-https
          - apt-utils
          - bash
          - bash-completion
          - ca-certificates
          - curl
          - dirmngr
          - gettext-base
          - gnupg2
          - language-pack-ru
          - make
          - openssh-client
          - python3
          - python3-apt
          - python3-distutils
          - python3-pip
          - software-properties-common
          - sshpass
          - wget
        state: latest
    - name: Install KDE specific software
      apt: 
        force_apt_get: yes
        name: 
          - language-pack-kde-ru
          - usb-creator-kde
        state: latest
      when: ansible_os_family == 'Debian' and ansible_env.XDG_CURRENT_DESKTOP is defined and ansible_env.XDG_CURRENT_DESKTOP == "KDE"
    - name: Install Gnome specific software
      apt: 
        force_apt_get: yes
        name: 
          - language-pack-gnome-ru
          - usb-creator-gtk
          - variety
          - gnome-tweak-tool
        state: latest
      when: ansible_os_family == 'Debian' and ansible_env.XDG_CURRENT_DESKTOP is defined and ansible_env.XDG_CURRENT_DESKTOP == "GNOME"
