---
- hosts: localhost
  connection: local
  tasks:
    - apt_key: url='{{item}}' state=present
      with_items:
        - https://download.docker.com/linux/ubuntu/gpg
    - apt_repository: repo='{{item}}' state=present update_cache=yes
      with_items:
        - deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        # - ppa:phoerious/keepassxc # @TODO:
    - apt:
        force_apt_get: yes
        name:
          - keepassxc
          - git
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
    - apt: force_apt_get=yes deb='{{item}}'
      with_items:
      - https://update.code.visualstudio.com/latest/linux-deb-x64/stable
      - https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
    - get_url: url=https://dl.pstmn.io/download/latest/linux64 dest={{ current_home }}/soft/postman.tar.gz
    - command: code --install-extension={{ item }} --user-data-dir={{ ansible_user_dir }}/.config/Code/
      with_items:
        - ms-azuretools.vscode-docker
        - mikestead.dotenv
        - codezombiech.gitignore
        - yzhang.markdown-all-in-one
        - christian-kohler.path-intellisense
        - ms-vscode-remote.vscode-remote-extensionpack
        - wayou.vscode-todo-highlight
        - redhat.vscode-yaml
    - group: name=docker state=present
    - user: name="{{ current_user }}" groups=docker append=yes
    - pip:
        executable: pip3
        name:
          - docker
          - docker-compose
        state: latest
      # @TODO: arduino