---
- hosts: localhost
  connection: local
  tasks:
    - apt: force_apt_get=yes deb='{{item}}'
      with_items:
      - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - https://download3.operacdn.com/pub/opera/desktop/86.0.4363.50/linux/opera-stable_86.0.4363.50_amd64.deb
      ignore_errors: yes
