---
- hosts: localhost
  connection: local
  tasks:
    - debug: msg='Install vpn'
    - block:
      - apt:
          force_apt_get: yes
          state: latest
          name:
            - openvpn
            - network-manager-openvpn
            - openconnect
            - wireguard
      when: ansible_os_family == 'Debian' # @TODO: ubuntu
# @TODO: manjaro
# @TODO: fedora
