---
- hosts: localhost
  connection: local
  tasks:
    - debug: msg='Install postman'
    - block:
      - file: 
          state: directory
          force: no
          path: "{{ current_home }}/soft"
      - get_url:
          url: https://dl.pstmn.io/download/latest/linux64
          dest: "{{ current_home }}/soft/postman.tar.gz"

      when: ansible_os_family == 'Debian' # @TODO: ubuntu
# @TODO: manjaro
# @TODO: fedora
