---
- hosts: localhost
  connection: local
  tasks:
    - debug: msg='Install discord'
    - block:
      - apt: 
          force_apt_get: yes
          deb: https://discord.com/api/download?platform=linux&format=deb
      when: ansible_os_family == 'Debian' # @TODO: ubuntu
# @TODO: manjaro
# @TODO: fedora
