---
- hosts: localhost
  connection: local
  tasks:
    - debug: msg='Install telegram'
    - block:
      - file:
          state: directory
          force: no
          path: "{{ current_home }}/soft"
      - get_url:
          url: https://telegram.org/dl/desktop/linux
          dest: "{{ current_home }}/soft/telegram.tar.xz"
      when: ansible_os_family == 'Debian' # @TODO: ubuntu
# @TODO: manjaro
# @TODO: fedora
