---
- hosts: localhost
  connection: local
  tasks:
    - debug: msg='Install chromium'
    - block:
      - apt:
          force_apt_get: yes
          name:
            - chromium-browser
      when: ansible_os_family == 'Debian' # @TODO: ubuntu
# @TODO: manjaro
# @TODO: fedora
