- name: install docker
  community.general.pacman:
    state: present
    name:
    - docker
    - docker-compose
  become: yes

- name: start docker
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: docker
  become: yes
