- import_tasks: manjaro/repos.yml
  when: ansible_facts.lsb.id == 'ManjaroLinux'
# @TODO: ubuntu
# @TODO: fedora

- import_tasks: manjaro/utils.yml
  when: ansible_facts.lsb.id == 'ManjaroLinux'
# @TODO: ubuntu
# @TODO: fedora