name: Testing

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} test
    strategy:
      matrix:
        os: [ubuntu:20.04, ubuntu:22.04]
    steps:
    - uses: actions/checkout@v3
    - name: Prepare
      run: |
        apt-get update
        apt-get install --no-install-recommends -y make ansible
    - run: make deploy 
    - run: make _test
    - run: make update
    - run: make show-tasks