name: Testing

on:
  push:
    branches:
      - master

jobs:
  test:
    name: check ${{ matrix.os }}
    runs-on: ubuntu-latest
    container: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu:20.04
          - ubuntu:22.04
    steps:
    - uses: actions/checkout@v3
    - run: apt-get update && apt-get install --no-install-recommends -y sudo make ansible
    - run: make install-base 
    - run: make install-internet
    - run: make install-office
    - run: make install-coding
    - run: make install-guitar
