name: Testing

on:
  push:
    branches:
      - master

jobs:
  test:
    name: check ${{ matrix.os }}
    # runs-on: ubuntu-latest
    # container: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-20.04
          - ubuntu-22.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get update && sudo apt-get install --no-install-recommends -y sudo make ansible
    - run: sudo make deploy
    - run: make _test
    - run: make update
    - run: make show-tasks